# Generated by Django 6.0.4 on 2026-05-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='available',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='slug',
        ),
        migrations.AddField(
            model_name='booking',
            name='client_name',
            field=models.CharField(default='000', max_length=100, verbose_name='Имя клиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(default='000', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='people_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество человек'),
        ),
        migrations.AddField(
            model_name='tour',
            name='available_slots',
            field=models.PositiveIntegerField(default=10, verbose_name='Количество мест'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='end_date',
            field=models.DateField(default='2024-05-03', verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateField(default='2024-05-03', verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Фото тура'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
