# Generated by Django 6.0.4 on 2026-05-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_alter_booking_options_alter_tour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('hotel', 'Отели'), ('guesthouse', 'Гостевые дома'), ('house', 'Дома'), ('flat', 'Квартиры'), ('hostel', 'Хостелы'), ('camp', 'Базы отдыха')], default='hotel', max_length=20, verbose_name='Тип жилья'),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(default='Сочи', max_length=100, verbose_name='Город/Локация'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='people_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во человек'),
        ),
    ]
