# Generated by Django 6.0.4 on 2026-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_tour_category_tour_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='service_type',
            field=models.CharField(choices=[('stay', 'Проживание'), ('tour', 'Экскурсии и туры')], default='stay', max_length=10, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='available_slots',
            field=models.PositiveIntegerField(verbose_name='Свободно мест/номеров'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('hotel', 'Отели'), ('guesthouse', 'Гостевые дома'), ('house', 'Дома'), ('flat', 'Квартиры'), ('hostel', 'Хостелы')], default='hotel', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tours/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(default='Сочи', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (за сутки/за тур)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
