# Generated by Django 6.0.4 on 2026-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_tour_service_type_alter_tour_available_slots_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты (Туры и Жилье)'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='available_slots',
            field=models.PositiveIntegerField(default=10, verbose_name='Свободные места'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('hotels', 'Отели'), ('apartments', 'Квартиры'), ('houses', 'Дома/Коттеджи'), ('excursion', 'Экскурсия'), ('active', 'Активный отдых'), ('multi_day', 'Многодневный тур')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='service_type',
            field=models.CharField(choices=[('stay', 'Проживание'), ('tour', 'Экскурсия/Тур')], max_length=10, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
    ]
